package net.trollyloki.jicsit.server.https.trustmanager;

import net.trollyloki.jicsit.server.https.CertificateUtils;
import org.jspecify.annotations.NullMarked;

import javax.net.ssl.SSLEngine;
import javax.net.ssl.X509ExtendedTrustManager;
import java.net.Socket;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;

/**
 * A trust manager that decides if certificates are trusted based on their fingerprint.
 * Subclasses must implement {@link #checkFingerprintTrusted(String)}.
 * <p>
 * This generates server certificate fingerprints in the same way that the game does,
 * which will likely <strong>not match</strong> fingerprints generated by common algorithms.
 * The fingerprints will match those <strong>displayed by the game</strong> (although without the "SHA256:" prefix).
 *
 * @see CertificateUtils#getFingerprint(Certificate)
 */
@NullMarked
public abstract class FingerprintBasedTrustManager extends X509ExtendedTrustManager {

    /**
     * Creates a new fingerprint-based trust manager that only trusts certificates with a specific fingerprint.
     *
     * @param fingerprint trusted certificate fingerprint
     * @return new {@link FingerprintBasedTrustManager}
     */
    public static FingerprintBasedTrustManager of(String fingerprint) {
        return new FingerprintBasedTrustManager() {
            @Override
            protected void checkFingerprintTrusted(String f) throws CertificateException {
                if (!f.equals(fingerprint)) {
                    throw new CertificateException("Untrusted server fingerprint: " + f);
                }
            }
        };
    }

    /**
     * Checks if a certificate is trusted based on its fingerprint.
     *
     * @param fingerprint certificate fingerprint
     * @throws CertificateException if the certificate is not trusted
     */
    protected abstract void checkFingerprintTrusted(String fingerprint) throws CertificateException;

    @Override
    public X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[0];
    }

    private void checkFingerprintTrusted(X509Certificate[] chain) throws CertificateException {
        checkFingerprintTrusted(CertificateUtils.getFingerprint(chain[0]));
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        checkFingerprintTrusted(chain);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        checkFingerprintTrusted(chain);
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType, Socket socket) throws CertificateException {
        checkFingerprintTrusted(chain);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType, Socket socket) throws CertificateException {
        checkFingerprintTrusted(chain);
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType, SSLEngine engine) throws CertificateException {
        checkFingerprintTrusted(chain);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType, SSLEngine engine) throws CertificateException {
        checkFingerprintTrusted(chain);
    }

}
