package net.trollyloki.jicsit.server.https.trustmanager;

import net.trollyloki.jicsit.server.https.CertificateUtils;
import org.jspecify.annotations.NonNull;

import javax.net.ssl.SSLEngine;
import javax.net.ssl.X509ExtendedTrustManager;
import java.net.Socket;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * A trust manager that only trusts certificates with specific fingerprint(s).
 *
 * @see CertificateUtils#getFingerprint(Certificate)
 */
public class FingerprintBasedTrustManager extends X509ExtendedTrustManager {

    private final @NonNull Set<String> fingerprints;

    /**
     * Creates a new fingerprint-based trust manager.
     * <p>
     * This generates server certificate fingerprints in the same way that the game does,
     * which will likely <strong>not match</strong> fingerprints generated by common algorithms.
     * The provided fingerprints must be ones <strong>displayed by the game</strong>
     * (although without the "SHA256:" prefix).
     *
     * @param fingerprints collection of trusted certificate fingerprints
     */
    public FingerprintBasedTrustManager(@NonNull Collection<String> fingerprints) {
        this.fingerprints = new HashSet<>(fingerprints);
    }

    /**
     * Creates a new fingerprint-based trust manager.
     * <p>
     * This generates server certificate fingerprints in the same way that the game does,
     * which will likely <strong>not match</strong> fingerprints generated by common algorithms.
     * The provided fingerprint must be one <strong>displayed by the game</strong>
     * (although without the "SHA256:" prefix).
     *
     * @param fingerprint trusted certificate fingerprint
     * @see #FingerprintBasedTrustManager(Collection)
     */
    public FingerprintBasedTrustManager(String fingerprint) {
        this.fingerprints = Collections.singleton(fingerprint);
    }

    @Override
    public X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[0];
    }

    private void checkFingerprint(X509Certificate[] chain) throws CertificateException {
        String serverFingerprint = CertificateUtils.getFingerprint(chain[0]);
        for (String fingerprint : fingerprints) {
            if (serverFingerprint.equals(fingerprint))
                return;
        }
        throw new CertificateException("Untrusted server fingerprint: " + serverFingerprint);
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        checkFingerprint(chain);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        checkFingerprint(chain);
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType, Socket socket) throws CertificateException {
        checkFingerprint(chain);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType, Socket socket) throws CertificateException {
        checkFingerprint(chain);
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType, SSLEngine engine) throws CertificateException {
        checkFingerprint(chain);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType, SSLEngine engine) throws CertificateException {
        checkFingerprint(chain);
    }

}
